// Code generated by protoc-gen-go. DO NOT EDIT.
// source: crawler.proto

package go_grpc_srv_reptiles

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SaveItemRequest struct {
	Item                 *Item    `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveItemRequest) Reset()         { *m = SaveItemRequest{} }
func (m *SaveItemRequest) String() string { return proto.CompactTextString(m) }
func (*SaveItemRequest) ProtoMessage()    {}
func (*SaveItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{0}
}

func (m *SaveItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveItemRequest.Unmarshal(m, b)
}
func (m *SaveItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveItemRequest.Marshal(b, m, deterministic)
}
func (m *SaveItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveItemRequest.Merge(m, src)
}
func (m *SaveItemRequest) XXX_Size() int {
	return xxx_messageInfo_SaveItemRequest.Size(m)
}
func (m *SaveItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveItemRequest proto.InternalMessageInfo

func (m *SaveItemRequest) GetItem() *Item {
	if m != nil {
		return m.Item
	}
	return nil
}

type SaveItemResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveItemResult) Reset()         { *m = SaveItemResult{} }
func (m *SaveItemResult) String() string { return proto.CompactTextString(m) }
func (*SaveItemResult) ProtoMessage()    {}
func (*SaveItemResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{1}
}

func (m *SaveItemResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveItemResult.Unmarshal(m, b)
}
func (m *SaveItemResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveItemResult.Marshal(b, m, deterministic)
}
func (m *SaveItemResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveItemResult.Merge(m, src)
}
func (m *SaveItemResult) XXX_Size() int {
	return xxx_messageInfo_SaveItemResult.Size(m)
}
func (m *SaveItemResult) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveItemResult.DiscardUnknown(m)
}

var xxx_messageInfo_SaveItemResult proto.InternalMessageInfo

type ProcessRequest struct {
	Url                  string            `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	SerializedParser     *SerializedParser `protobuf:"bytes,2,opt,name=serializedParser,proto3" json:"serializedParser,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ProcessRequest) Reset()         { *m = ProcessRequest{} }
func (m *ProcessRequest) String() string { return proto.CompactTextString(m) }
func (*ProcessRequest) ProtoMessage()    {}
func (*ProcessRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{2}
}

func (m *ProcessRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessRequest.Unmarshal(m, b)
}
func (m *ProcessRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessRequest.Marshal(b, m, deterministic)
}
func (m *ProcessRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessRequest.Merge(m, src)
}
func (m *ProcessRequest) XXX_Size() int {
	return xxx_messageInfo_ProcessRequest.Size(m)
}
func (m *ProcessRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessRequest proto.InternalMessageInfo

func (m *ProcessRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *ProcessRequest) GetSerializedParser() *SerializedParser {
	if m != nil {
		return m.SerializedParser
	}
	return nil
}

type SerializedParser struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Args                 string   `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SerializedParser) Reset()         { *m = SerializedParser{} }
func (m *SerializedParser) String() string { return proto.CompactTextString(m) }
func (*SerializedParser) ProtoMessage()    {}
func (*SerializedParser) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{3}
}

func (m *SerializedParser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SerializedParser.Unmarshal(m, b)
}
func (m *SerializedParser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SerializedParser.Marshal(b, m, deterministic)
}
func (m *SerializedParser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SerializedParser.Merge(m, src)
}
func (m *SerializedParser) XXX_Size() int {
	return xxx_messageInfo_SerializedParser.Size(m)
}
func (m *SerializedParser) XXX_DiscardUnknown() {
	xxx_messageInfo_SerializedParser.DiscardUnknown(m)
}

var xxx_messageInfo_SerializedParser proto.InternalMessageInfo

func (m *SerializedParser) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SerializedParser) GetArgs() string {
	if m != nil {
		return m.Args
	}
	return ""
}

type ProcessResult struct {
	Item                 []*Item           `protobuf:"bytes,1,rep,name=item,proto3" json:"item,omitempty"`
	Request              []*ProcessRequest `protobuf:"bytes,2,rep,name=request,proto3" json:"request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ProcessResult) Reset()         { *m = ProcessResult{} }
func (m *ProcessResult) String() string { return proto.CompactTextString(m) }
func (*ProcessResult) ProtoMessage()    {}
func (*ProcessResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{4}
}

func (m *ProcessResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessResult.Unmarshal(m, b)
}
func (m *ProcessResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessResult.Marshal(b, m, deterministic)
}
func (m *ProcessResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessResult.Merge(m, src)
}
func (m *ProcessResult) XXX_Size() int {
	return xxx_messageInfo_ProcessResult.Size(m)
}
func (m *ProcessResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessResult.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessResult proto.InternalMessageInfo

func (m *ProcessResult) GetItem() []*Item {
	if m != nil {
		return m.Item
	}
	return nil
}

func (m *ProcessResult) GetRequest() []*ProcessRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

type Item struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Payload              string   `protobuf:"bytes,4,opt,name=Payload,proto3" json:"Payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_84c7eabcfe7807d1, []int{5}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Item) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Item) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Item) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

func init() {
	proto.RegisterType((*SaveItemRequest)(nil), "go.grpc.srv.reptiles.SaveItemRequest")
	proto.RegisterType((*SaveItemResult)(nil), "go.grpc.srv.reptiles.SaveItemResult")
	proto.RegisterType((*ProcessRequest)(nil), "go.grpc.srv.reptiles.ProcessRequest")
	proto.RegisterType((*SerializedParser)(nil), "go.grpc.srv.reptiles.SerializedParser")
	proto.RegisterType((*ProcessResult)(nil), "go.grpc.srv.reptiles.ProcessResult")
	proto.RegisterType((*Item)(nil), "go.grpc.srv.reptiles.Item")
}

func init() { proto.RegisterFile("crawler.proto", fileDescriptor_84c7eabcfe7807d1) }

var fileDescriptor_84c7eabcfe7807d1 = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4f, 0x4f, 0xfa, 0x40,
	0x10, 0xfd, 0x51, 0x9a, 0x1f, 0x30, 0x06, 0x6c, 0x26, 0x1e, 0x1a, 0x4e, 0xa6, 0xa2, 0xf1, 0xb4,
	0x07, 0xbc, 0x79, 0x30, 0xf1, 0xe8, 0x8d, 0x94, 0x84, 0xc4, 0xe3, 0x4a, 0x27, 0xa4, 0xc9, 0x62,
	0xeb, 0xec, 0x52, 0x83, 0x17, 0x3f, 0x99, 0xdf, 0xcd, 0x74, 0x60, 0x55, 0xb0, 0x06, 0x6e, 0xb3,
	0x93, 0xf7, 0x67, 0xdf, 0xdb, 0x85, 0xfe, 0x9c, 0xf5, 0xab, 0x21, 0x56, 0x25, 0x17, 0xae, 0xc0,
	0xb3, 0x45, 0xa1, 0x16, 0x5c, 0xce, 0x95, 0xe5, 0x4a, 0x31, 0x95, 0x2e, 0x37, 0x64, 0x93, 0x7b,
	0x38, 0x9d, 0xea, 0x8a, 0x1e, 0x1c, 0x2d, 0x53, 0x7a, 0x59, 0x91, 0x75, 0xa8, 0x20, 0xcc, 0x1d,
	0x2d, 0xe3, 0xd6, 0x79, 0xeb, 0xfa, 0x64, 0x3c, 0x54, 0x4d, 0x3c, 0x25, 0x04, 0xc1, 0x25, 0x11,
	0x0c, 0xbe, 0x25, 0xec, 0xca, 0xb8, 0xa4, 0x82, 0xc1, 0x84, 0x8b, 0x39, 0x59, 0xeb, 0x35, 0x23,
	0x68, 0xaf, 0xd8, 0x88, 0x64, 0x2f, 0xad, 0x47, 0x4c, 0x21, 0xb2, 0xc4, 0xb9, 0x36, 0xf9, 0x1b,
	0x65, 0x13, 0xcd, 0x96, 0x38, 0x0e, 0xc4, 0xf1, 0xaa, 0xd9, 0x71, 0xba, 0x87, 0x4e, 0x7f, 0xf1,
	0x93, 0x5b, 0x88, 0xf6, 0x51, 0x88, 0x10, 0x3e, 0xeb, 0x25, 0x6d, 0xad, 0x65, 0xae, 0x77, 0x9a,
	0x17, 0x56, 0xfc, 0x7a, 0xa9, 0xcc, 0xc9, 0x3b, 0xf4, 0xbf, 0xee, 0x5c, 0x87, 0xf8, 0x51, 0x43,
	0xfb, 0x98, 0x1a, 0xf0, 0x0e, 0x3a, 0xbc, 0x49, 0x1b, 0x07, 0x42, 0x19, 0x35, 0x53, 0x76, 0x9b,
	0x49, 0x3d, 0x29, 0x99, 0x41, 0x58, 0xab, 0x35, 0x54, 0x85, 0x10, 0xba, 0x75, 0x49, 0xfe, 0xba,
	0xf5, 0x8c, 0x03, 0x08, 0xf2, 0x2c, 0x6e, 0xcb, 0x26, 0xc8, 0x33, 0x8c, 0xa1, 0x33, 0xd1, 0x6b,
	0x53, 0xe8, 0x2c, 0x0e, 0x65, 0xe9, 0x8f, 0xe3, 0x8f, 0x16, 0x74, 0xbd, 0x39, 0x3e, 0x42, 0xd7,
	0xbf, 0x15, 0x5e, 0xfe, 0xd1, 0xf3, 0xee, 0x77, 0x18, 0x8e, 0x0e, 0xc1, 0xe4, 0xc9, 0xff, 0xe1,
	0x0c, 0x3a, 0xdb, 0x68, 0x78, 0x54, 0xf2, 0xe1, 0xc5, 0x01, 0xd4, 0x46, 0xf7, 0xe9, 0xbf, 0x7c,
	0xdf, 0x9b, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd7, 0x12, 0xcc, 0x68, 0xcf, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ReptilesClient is the client API for Reptiles service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReptilesClient interface {
	SaveItem(ctx context.Context, in *SaveItemRequest, opts ...grpc.CallOption) (*SaveItemResult, error)
	Process(ctx context.Context, in *ProcessRequest, opts ...grpc.CallOption) (*ProcessResult, error)
}

type reptilesClient struct {
	cc *grpc.ClientConn
}

func NewReptilesClient(cc *grpc.ClientConn) ReptilesClient {
	return &reptilesClient{cc}
}

func (c *reptilesClient) SaveItem(ctx context.Context, in *SaveItemRequest, opts ...grpc.CallOption) (*SaveItemResult, error) {
	out := new(SaveItemResult)
	err := c.cc.Invoke(ctx, "/go.grpc.srv.reptiles.reptiles/SaveItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reptilesClient) Process(ctx context.Context, in *ProcessRequest, opts ...grpc.CallOption) (*ProcessResult, error) {
	out := new(ProcessResult)
	err := c.cc.Invoke(ctx, "/go.grpc.srv.reptiles.reptiles/Process", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReptilesServer is the server API for Reptiles service.
type ReptilesServer interface {
	SaveItem(context.Context, *SaveItemRequest) (*SaveItemResult, error)
	Process(context.Context, *ProcessRequest) (*ProcessResult, error)
}

// UnimplementedReptilesServer can be embedded to have forward compatible implementations.
type UnimplementedReptilesServer struct {
}

func (*UnimplementedReptilesServer) SaveItem(ctx context.Context, req *SaveItemRequest) (*SaveItemResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveItem not implemented")
}
func (*UnimplementedReptilesServer) Process(ctx context.Context, req *ProcessRequest) (*ProcessResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Process not implemented")
}

func RegisterReptilesServer(s *grpc.Server, srv ReptilesServer) {
	s.RegisterService(&_Reptiles_serviceDesc, srv)
}

func _Reptiles_SaveItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReptilesServer).SaveItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.grpc.srv.reptiles.reptiles/SaveItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReptilesServer).SaveItem(ctx, req.(*SaveItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Reptiles_Process_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReptilesServer).Process(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/go.grpc.srv.reptiles.reptiles/Process",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReptilesServer).Process(ctx, req.(*ProcessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Reptiles_serviceDesc = grpc.ServiceDesc{
	ServiceName: "go.grpc.srv.reptiles.reptiles",
	HandlerType: (*ReptilesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SaveItem",
			Handler:    _Reptiles_SaveItem_Handler,
		},
		{
			MethodName: "Process",
			Handler:    _Reptiles_Process_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "crawler.proto",
}
